name: Build & Attach archive on release

on:
  release:
    types: [published]

# enable github actions token write permissions
permissions:
  contents: write

jobs:
  build:
    name: Build & Attach
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      # install frontend dependencies
      - name: Install frontend dependencies
        run: npm install --loglevel=error

      # build frontend assets
      - name: Build assets
        run: npm run build

      # create release asset archive without unnecessary files
      - name: Create release archive
        run: |
          tar --warning=no-file-changed -czf ${{ github.event.repository.name }}-${{ github.ref_name }}-webapp.tar.gz \
            ./dist || true

      # upload release asset archive
      - name: Upload release asset
        uses: softprops/action-gh-release@v2
        with:
          files: ${{ github.event.repository.name }}-${{ github.ref_name }}-webapp.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # build electron app
      - name: Build electron app
        run: |
          export ELECTRON_BUILDER_CACHE=/tmp/electron-builder-cache
          npm run electron-dist

      # upload appimage to release
      - name: Upload appimage to release
        uses: softprops/action-gh-release@v2
        with:
          files: dist/*.AppImage
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # upload snap to release
      - name: Upload snap to release
        uses: softprops/action-gh-release@v2
        with:
          files: dist/*.snap
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
